swagger: "2.0"
info:
  title: "mvtest"
  description: "mvtest is an API to manage exams."
  version: "1.0.0"
  license:
    name: "GPLv3"
    url: "https://github.com/CarlottaTagliaro/mvtest/blob/master/LICENSE"
schemes:
- "https"
host: "mvtest-develop.herokuapp.com"
basePath: "/v1"
tags:
- name: "task"
  description: "Find everything about your tasks"
- name: "exam"
  description: "Find everything about your exams"
- name: "class"
  description: "Find everything about your classes"
- name: "assignment"
  description: "Find everything about your assignments"
- name: "review"
  description: "Find everything about your reviews"
- name: "session"
  description: "Find everything about the current session"
consumes:
- "application/json"
produces:
- "application/json"
paths:

  /task:
    get:
      tags:
      - "task"
      summary: "List all tasks the user has access to"
      responses:
        200:
          $ref: "#/responses/200Task"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      tags:
      - "task"
      summary: "Create a task"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/TaskRequest"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /task/{taskId}:
    get:
      tags:
      - "task"
      summary: "Find task by id"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of the task to return"
        required: true
        type: "integer"
      responses:
        200:
          $ref: "#/responses/200Task"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    post:
      tags:
      - "task"
      summary: "Edits a task"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of the task to edit"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/TaskRequest"
      responses:
        200:
          $ref: "#/responses/200"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    delete:
      tags:
      - "task"
      summary: "Deletes a task"
      parameters:
      - name: "taskId"
        in: "path"
        description: "ID of the task to delete"
        required: true
        type: "integer"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  
  /exam:
    get:
      tags:
      - "exam"
      summary: "List all exams the user has access to"
      responses:
        200:
          $ref: "#/responses/200Exam"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      tags:
      - "exam"
      summary: "Creates an exam"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Exam"
      responses:
        201:
          $ref: "#/responses/201"
          202:
          $ref: "#/responses/202"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /exam/{examId}:
    get:
      tags:
      - "exam"
      summary: "Find exam by ID"
      parameters:
      - name: "examId"
        in: "path"
        description: "ID of the exam to return"
        required: true
        type: "integer"
      responses:
        200:
          $ref: "#/responses/200Exam"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    delete:
      tags:
      - "exam"
      summary: "Deletes an exam"
      parameters:
      - name: "examId"
        in: "path"
        description: "ID of the exam to delete"
        required: true
        type: "integer"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      tags:
      - "exam"
      summary: "Adds a Task to an Exam"
      parameters:
      - name: "examId"
        in: "path"
        description: "ID of the exam to return"
        required: true
        type: "integer"
      - in: "body"
        name: "task id"
        schema: 
          type: "array"
          items:
            type: "number"
          example:
            - 1
            - 2
            - 3
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /exams/{examId}/{taskId}:
    delete:
      tags:
      - "exam"
      summary: "Deletes a specific task in an exam"
      parameters:
      - name: "examId"
        in: "path"
        description: "ID of the exam to return"
        required: true
        type: "integer"
      - name: "taskId"
        in: "path"
        required: true
        description: "ID of the task to delete"
        type: "integer"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

  /class:
    get:
      tags:
      - "class"
      summary: "Lists all classes the user belongs to"
      responses:
        200:
          $ref: "#/responses/200Class"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      tags:
      - "class"
      summary: "Creates a new class"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: '#/definitions/ClassRequest'
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /class/{classId}:
    get:
      tags:
      - "class"
      summary: "Find a class by ID"
      parameters:
      - name: "classId"
        in: "path"
        description: I"D of the class to retrieve"
        required: true
        type: "integer"
      responses:
        200:
          $ref: "#/responses/200Class"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    post:
      tags:
      - "class"
      summary: "Edits a class"
      parameters:
      - name: "classId"
        in: "path"
        description: "ID of the class to edit"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: '#/definitions/ClassRequest'
      responses:
        200:
          $ref: "#/responses/200"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    delete:
      tags:
      - "class"
      summary: "Deletes a class"
      parameters:
      - name: "classId"
        in: "path"
        description: "ID of the class to delete"
        required: true
        type: "integer"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
          
  /assignment:
    get:
      tags: 
      - "assignment"
      summary: "Get all assignments you've done"
      responses:
        200:
          $ref: "#/responses/200Assignment"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put: 
      tags:
      - "assignment"
      summary: "Creates a new assignment"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: '#/definitions/AssignmentRequest'
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /assignment/{assignmentId}:
    get:
      tags:
      - "assignment"
      summary: "Find assignment by id"
      parameters:
      - name: "assignmentId"
        in: "path"
        description: "ID of the assignment to return"
        required: true
        type: "integer"
      responses:
        200:
          $ref: "#/responses/200Assignment"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    post:
      tags:
      - "assignment"
      summary: "Edits an assignment"
      parameters:
      - name: "assignmentId"
        in: "path"
        description: "ID of the assignment to edit"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: '#/definitions/AssignmentRequest'
      responses:
        200:
          $ref: "#/responses/200"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    delete:
      tags:
      - "assignment"
      summary: "Deletes an assignment"
      parameters:
      - name: "assignmentId"
        in: "path"
        description: "ID of the assignment to delete"
        required: true
        type: "integer"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /assignment/{assignmentId}/submission:
    get:
      tags: 
      - "assignment"
      summary: "Get all submission you've done for that assignment"
      parameters:
        - name: "assignmentId"
          in: "path"
          description: "ID of the assignment"
          required: true
          type: "integer"
      responses:
        200:
          $ref: "#/responses/200AssignmentSubmission"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put: #post cause we have to store all the submission, it is not possible to modify them
      tags:
      - "assignment"
      summary: "Create a new submission"
      parameters:
      - name: "assignmentId"
        in: "path"
        description: "ID of the assignment"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SubmissionRequest"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    delete:
      tags:
      - "assignment"
      summary: "deletes all submission for an assignment" #retire
      parameters:
      - name: "assignmentId"
        in: "path"
        required: true
        type: "integer"
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    
  /review:
    get:
      tags:
      - "review"
      summary: "Get all reviews you've done"
      responses:
        200:
          $ref: "#/responses/200AssignmentSubmission"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      tags:
      - "review"
      summary: "Create a new review"
      parameters:
      - name: "body"
        in: "body"
        required: true  
        schema:
          $ref: '#/definitions/ReviewRequest'
      responses:
        201:
          $ref: "#/responses/201"
        202:
          $ref: "#/responses/202"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
  /review/{reviewId}:
    post:
      tags:
      - "review"
      summary: "Edit a specific review"
      parameters:
      - name: "reviewId"
        in: "path"
        required: true
        type: "number"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: '#/definitions/ReviewRequest'
      responses:
        200:
          $ref: "#/responses/200"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

  /auth/session:
    get:
      tags:
      - "session"
      summary: "Returns the user in the session"
      produces:
      - "text/plain"
      responses:
        200:
          $ref: "#/responses/200Session"
        304:
          $ref: "#/responses/304"
        401:
          $ref: "#/responses/401"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    put:
      tags:
      - "session"
      summary: "Authenticates a user"
      produces:
      - "text/plain"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          properties:
            username:
              type: "string"
              format: "email"
            password:
              type: "string"
              format: "password"
      responses:
        200:
          $ref: "#/responses/200Session"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"
    delete:
      tags:
      - "session"
      summary: "Logs a user out"
      responses:
        204:
          $ref: "#/responses/204"
        403:
          $ref: "#/responses/403"
        404:
          $ref: "#/responses/404"
        500:
          $ref: "#/responses/500"

responses:
    200:
      description: "OK"
    200Task:
      description: "OK"
      schema:
        type: "array"
        items:
          $ref: "#/definitions/Task"
    200Exam:
      description: "OK"
      schema:
        type: "array"
        items:
          $ref: "#/definitions/Exam"
    200Class:
      description: "OK"
      schema:
        type: "array"
        items:
          $ref: "#/definitions/Class"
    200Assignment:
      description: "OK"
      schema:
        type: "array"
        items:
          $ref: "#/definitions/Assignment"
    200AssignmentSubmission:
      description: "OK"
      schema:
        type: "array"
        items:
          $ref: "#/definitions/Submission"
    200Review:
      description: "OK"
      schema:
        type: "array"
        items:
          $ref: "#/definitions/Review"
    200Session:
          description: "Ok"
          schema:
            $ref: "#/definitions/User"
    201:
      description: "Created"
    202:
      description: "Accepted"
    204:
      description: "No Content"
    304:
      description: "Not Modified"
    401:
      description: "Unauthorized"
    403:
      description: "Forbidden"
    404:
      description: "Not Found"
    500:
      description: "Internal Server Error"
      
definitions:
  Task:
    title: "Task"
    type: "object"
    properties:
      id:
        type: "number"
      question:
        type: "string"
      choices:
        type: "array"
        items:
          type: "string"
      users:
        type: "array"
        items:
          $ref: "#/definitions/UserPerms"
    required:
      - "id"
      - "question"
      - "choices"
    example:
      id:  0
      question: "Example question"
      type: 1
      choices:
        - "First Answer"
        - "Second Answer"
        - "Third Answer"
        - "Fourth Answer"
      users:
        - email: "owner@mail.com"
          owner: true
          canWrite: true
        - email: "user@mail.com"
          owner: false
          canwrite: false
  User:
    title: "User"
    type: "object"
    properties:
      email:
        type: "string"
        format: "email"
      name:
        type: "string"
    example:
      email: "user@mail.com"
      name: "User Name"
  ClassRequest:
    title: "ClassRequest"
    type: "object"
    properties:
      name:
        type: "string"
      users:
        type: "array"
        items:
          $ref: "#/definitions/User"
    example:
      name: "Software Engeneering"
      users:
      - email: "student@mail.com"
        name: "Good Student"
  Class:
    title: "Class"
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      users:
        type: "array"
        items:
          $ref: "#/definitions/User"
    example:
      id: 0
      name: "Software Engeneering"
      users:
      - email: "student@mail.com"
        name: "Good Student"
  Exam:
    title: "Exam"
    type: "object"
    properties: 
      id:
        type: "number"
      owner:
          $ref: "#/definitions/User"
      tasks:
        type: "array"
        items:
          type: "number"
    example:
      id: 0
      owner:
        email: "g.s@agg.it"
        name: "Mario"
      tasks:
        - 0
        - 1
  UserPerms:
    title: "User Perms"
    type: "object"
    properties:
      email:
        type: "string"
      owner:
        type: "boolean"
      canWrite:
        type: "boolean"
  TaskRequest:
    title: "Task Request"
    type: "object"
    properties:
      question:
        type: "string"
      choices:
        type: "array"
        items:
          type: "string"
    required:
      - "question"
      - "choices"
    example:
      question: "Example Question"
      choices:
        - "First Answer"
        - "Second Answer"
        - "Third Answer"
        - "Fourth Answer"
  AssignmentRequest:
    title: "AssignmentRequest"
    type: "object"
    properties: 
      deadline:
        type: "string"
        format: "date-time"
      review:
        type: "boolean"
      TA:
        $ref: "#/definitions/User"
      class:
        type: "array"
        items:
          $ref: "#/definitions/Class"
    example:
      deadline: "12-12-2018"
      review: true
      TA: 
        email: "g.s@agg.it"
        name: "Mario"
      class:
      - id: 0
        name: "Software Engeneering"
        users:
        - email: "student@mail.com"
          name: "Good Student"
  Assignment:
    title: "Assignment"
    type: "object"
    properties: 
      id:
        type: "number"
      deadline:
        type: "string"
        format: "date-time"
      review:
        type: "boolean"
      TA:
        $ref: "#/definitions/User"
      class:
        type: "array"
        items:
          $ref: "#/definitions/Class"
    example:
      id: 0
      deadline: "12-12-2018"
      review: true
      TA: 
        email: "g.s@agg.it"
        name: "Mario"
      class:
      - id: 0
        name: "Software Engeneering"
        users:
        - email: "student@mail.com"
          name: "Good Student"
  SubmissionRequest:
    title: "SubmissionRequest"
    type: "object"
    properties:
      answer:
        type: "string"
      time:
        type: "string"
        format: "date-time"
      task-id: 
        type: "number"
      Author: 
        $ref: "#/definitions/User" #is the id enough?
      assignment-id:
        type: "number"
    example:
      answer: "the correct answer is number 2"
      time: "12-12-2018"
      task-id: 3
      Author:
        email: "g.s@agg.com"
        name: "Giovanni Storti"
      assignment-id: 4
  Submission:
    title: "Submission"
    type: "object"
    properties:
      id:
        type: "number"
      answer:
        type: "string"
      time:
        type: "string"
        format: "date-time"
      task-id: 
        type: "number"
      Author: 
        $ref: "#/definitions/User" #is the id enough?
      assignment-id:
        type: "number"
    example:
      id: 0
      answer: "the correct answer is number 2"
      time: "12-12-2018"
      task-id: 3
      Author:
        email: "g.s@agg.com"
        name: "Giovanni Storti"
      assignment-id: 4
  ReviewRequest:
    title: "ReviewRequest"
    type: "object"
    properties:
      submission-id:
        type: "number"
      author:
        $ref: "#/definitions/User"
      mark:
        type: "number"
      comment:
        type: "string"
    example:
      submission-id : 1 
      author:
        email: "g.s@agg.com"
        name: "Giovanni Storti"
      mark: 27
      comment: "good work, well done"
  Review:
    title: "Review"
    type: "object"
    properties:
      id: 
        type: "number"
      submission-id:
        type: "number"
      author:
        $ref: "#/definitions/User"
      mark:
        type: "number"
      comment:
        type: "string"
    example:
      id: 0
      submission-id : 1 
      author:
        email: "g.s@agg.com"
        name: "Giovanni Storti"
      mark: 27
      comment: "good work, well done"
